import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function HomeLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<section
			className={`${inter.className} w-full flex flex-col items-center`}
		>
			<Navbar />
			<div className="w-full">{children}</div>
		</section>
	);
}
