import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Searchbar from './components/searchbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className}, flex flex-col items-center`}>
				<header className="my-2">
					<Searchbar />
				</header>
				{children}
			</body>
		</html>
	);
}
