import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Navbar from './(root)/components/navbar';
import SideMenu from '@/app/(root)/components/sidemenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className}`}>
				<header>
					<Navbar />
				</header>
				<div className="w-full flex flex-col sm:flex-row bg-colors-dark-400 relative ">
					<aside className=" bg-colors-dark-500 w-full h-[60px] text-xs sm:text-base overflow-hidden sm:h-screen sm:w-1/4 md:max-w-[200px] md:drop-shadow shadow-md shadow-colors-light-500  hover:shadow-colors-primary-500 hover:border-e-[1px] hover:border-colors-dark-200 transition-colors duration-700 ease-in-out">
						<SideMenu />
					</aside>
					<main className="bg-colors-dark-500 flex min-h-screen flex-col m-auto w-full ">
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
